export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  SESSION_REVOKED = 'SESSION_REVOKED',
  INVALID_OTP = 'INVALID_OTP',
  OTP_EXPIRED = 'OTP_EXPIRED',

  OUT_OF_STOCK = 'OUT_OF_STOCK',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  CART_EMPTY = 'CART_EMPTY',
  PRODUCT_NOT_ACTIVE = 'PRODUCT_NOT_ACTIVE',
  INVALID_PROMO_CODE = 'INVALID_PROMO_CODE',
  PROMO_CODE_EXPIRED = 'PROMO_CODE_EXPIRED',
  MERCHANT_NOT_LINKED = 'MERCHANT_NOT_LINKED',

  VALIDATION_FAILED = 'VALIDATION_FAILED',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
}
